export const ActionTypes = {
  FETCH_MOVIES: "FETCH_MOVIES",
  SET_MOVIES: "SET_MOVIES",
  SELECTED_MOVIE: "SELECTED_MOVIE",
  REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
  SEARCH_MOVIES: "SEARCH_MOVIES",
  LOADING: "LOADING",
};
